#!/bin/ansible-playbook

- hosts:
    - raspi-1
    - raspi-2
  become: yes
  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        autoremove: yes
        state: present
        pkg:
          - python3-pip
    - name: Install mqtt-io python package
      ansible.builtin.pip:
        name: mqtt-io
    - name: Create mqtt-io etc directory
      ansible.builtin.file:
        path: /etc/mqtt-io
        state: directory
        mode: '0755'
    - name: Install mqtt-io config.yaml
      ansible.builtin.template:
        src: "../{{name}}/mqtt-io-config.yaml"
        dest: /etc/mqtt-io/config.yaml
        owner: pi
        group: pi
        mode: '0644'
    - name: Install mqtt-io systemd unit file
      ansible.builtin.copy:
        src: "../mqtt-io/mqtt-io.service"
        dest: /etc/systemd/system/mqtt-io.service
        owner: pi
        group: pi
        mode: '0644'
    - name: Start mqtt-io service
      systemd: enabled=yes state=restarted name=mqtt-io daemon_reload=yes
